### PR TITLE
updated: grafana dashboard json with latest metrics-related changes

### LINKED ISSUE #5: Update grafana dashboard json with respect to latest metrics related changes

### PR DESCRIPTION
**Pull request by yashvardhan-kukreja**
Signed-off-by: Yashvardhan Kukreja <yash.kukreja.98@gmail.com>

closes #5

### CODE REVIEW

**Review by realshuting — APPROVED** [review]

**Comment by realshuting** [comment]
Thank @yashvardhan-kukreja!

How should we manage versioning stuff? We can use labels for different releases.

**Comment by yashvardhan-kukreja** [comment]
Actually, Grafana Dashboards already track a version history with the "version" field (checkout the last line Kyverno's Grafana Dashboard json).
So, we can just update that field everytime we cut a new release for the dashboard or for Kyverno :)

**Comment by realshuting** [comment]
@yashvardhan-kukreja - is this the version you are referring to?
https://github.com/kyverno/grafana-dashboard/blob/8a07a7de537dd6de8e79c54f4195713ca4c6de0f/grafana/dashboard.json#L2853

**Comment by yashvardhan-kukreja** [comment]
Yep :)

**Pull request merged**
